server:
  port: 9191
  error:
    include-message: always
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/registration_db
    username: postgres
    password: P@ssword1
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
