server:
  port: 9191
  error:
    include-message: always
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/registration_db
    username: postgres
    password: P@ssword1
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: example@gmail.com
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true